// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Active: typeof import('./components/UI/field/src/active.vue')['default']
    Aside: typeof import('./components/Layout/components/aside.vue')['default']
    'Aside.sub': typeof import('./components/Layout/components/aside.sub.vue')['default']
    'Bg.image': typeof import('./components/Items/bg.image.vue')['default']
    Breadcrumb: typeof import('./components/Layout/components/breadcrumb.vue')['default']
    Building: typeof import('./components/Items/building.vue')['default']
    Descriptions: typeof import('./components/UI/descriptions/src/descriptions.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    Empty: typeof import('./components/Items/empty.vue')['default']
    Field: typeof import('./components/UI/field/src/field.vue')['default']
    Grid: typeof import('./components/UI/grid/src/grid.vue')['default']
    'Grid.info': typeof import('./components/Items/grid.info.vue')['default']
    'Grid.item': typeof import('./components/UI/grid/src/grid.item.vue')['default']
    'Group.btn': typeof import('./components/UI/group-btn/src/group.btn.vue')['default']
    Header: typeof import('./components/Items/header.vue')['default']
    'Item.avatar': typeof import('./components/Items/item.avatar.vue')['default']
    'Item.block': typeof import('./components/Items/item.block.vue')['default']
    'Item.horizontal': typeof import('./components/Items/item.horizontal.vue')['default']
    'Item.progress': typeof import('./components/Items/item.progress.vue')['default']
    'Item.sort': typeof import('./components/Items/item.sort.vue')['default']
    'Item.vertical': typeof import('./components/Items/item.vertical.vue')['default']
    Layout: typeof import('./components/Layout/index.vue')['default']
    Main: typeof import('./components/Layout/components/main.vue')['default']
    Menu: typeof import('./components/UI/menu/src/menu.vue')['default']
    'Menu.vertical': typeof import('./components/Items/menu.vertical.vue')['default']
    Message: typeof import('./components/Layout/components/header/message.vue')['default']
    Pagination: typeof import('./components/UI/pagination/src/pagination.vue')['default']
    Personal: typeof import('./components/Layout/components/header/personal.vue')['default']
    Router: typeof import('./components/Layout/router.vue')['default']
    StepLine: typeof import('./components/UI/step/src/stepLine.vue')['default']
    'Sub.menu': typeof import('./components/UI/menu/src/sub.menu.vue')['default']
    UploadFile: typeof import('./components/UploadFile/index.vue')['default']
  }
}

export {}
